runtime: python37

handlers:

  - url: /(.*\.(gif|png|jpeg|jpg|css|js|ico|ttf))$
    static_files: dist/\1
    upload: dist/(.*)
    
  - url: /(.*)
    static_files: dist/index.html
    upload: dist/index.html